/* =========================================================
scoring_map_v1.js
CORE MATEMÁTICO COMPLETO DEL PIF
CFC CONTRACT V13 — FULL CLINICAL MAP
========================================================= */

export const SCORING_MAP_V1 = {

1:{A:{EVITADOR_FINANCIERO:3},B:{COMPENSADOR_EMOCIONAL:3},C:{RACIONAL_DESCONECTADO:2},D:{CONTROLADOR_ANSIOSO:2},E:{EVITADOR_FINANCIERO:3}},
2:{A:{ORDENADO_FUNCIONAL:1},B:{CONTROLADOR_ANSIOSO:2},C:{EVITADOR_FINANCIERO:3},D:{CONTROLADOR_ANSIOSO:3},E:{RACIONAL_DESCONECTADO:2}},
3:{A:{COMPENSADOR_EMOCIONAL:3},B:{COMPENSADOR_EMOCIONAL:2},C:{COMPENSADOR_EMOCIONAL:1},D:{DESORDENADO_CRONICO:2},E:{EVITADOR_FINANCIERO:2}},
4:{A:{EVITADOR_FINANCIERO:2},B:{CONTROLADOR_ANSIOSO:2},C:{ORDENADO_FUNCIONAL:1},D:{CONTROLADOR_ANSIOSO:1},E:{EVITADOR_FINANCIERO:2}},
5:{A:{AHORRADOR_SIN_PROPOSITO:2},B:{ASPIRACIONAL_DESALINEADO:2},C:{EVITADOR_FINANCIERO:2},D:{ORDENADO_FUNCIONAL:2},E:{CONTROLADOR_ANSIOSO:2}},
6:{A:{EVITADOR_FINANCIERO:2},B:{EVITADOR_FINANCIERO:3},C:{ORDENADO_FUNCIONAL:2},D:{CONTROLADOR_ANSIOSO:2},E:{RACIONAL_DESCONECTADO:2}},

7:{A:{COMPENSADOR_EMOCIONAL:2},B:{CONTROLADOR_ANSIOSO:2},C:{EVITADOR_FINANCIERO:2},D:{CONTROLADOR_ANSIOSO:3},E:{DESORDENADO_CRONICO:2}},
8:{A:{COMPENSADOR_EMOCIONAL:3},B:{DESORDENADO_CRONICO:2},C:{AHORRADOR_SIN_PROPOSITO:3},D:{ORDENADO_FUNCIONAL:2},E:{DESORDENADO_CRONICO:3}},
9:{A:{COMPENSADOR_EMOCIONAL:3},B:{DESORDENADO_CRONICO:2},C:{EVITADOR_FINANCIERO:2},D:{ORDENADO_FUNCIONAL:2},E:{DESORDENADO_CRONICO:3}},
10:{A:{EVITADOR_FINANCIERO:2},B:{COMPENSADOR_EMOCIONAL:3},C:{COMPENSADOR_EMOCIONAL:2},D:{ORDENADO_FUNCIONAL:2},E:{DESORDENADO_CRONICO:2}},
11:{A:{COMPENSADOR_EMOCIONAL:2},B:{CONTROLADOR_ANSIOSO:2},C:{AHORRADOR_SIN_PROPOSITO:2},D:{ORDENADO_FUNCIONAL:2},E:{EVITADOR_FINANCIERO:2}},
12:{A:{CONTROLADOR_ANSIOSO:3},B:{RACIONAL_DESCONECTADO:2},C:{DESORDENADO_CRONICO:2},D:{ORDENADO_FUNCIONAL:2},E:{CONTROLADOR_ANSIOSO:2}},

13:{A:{COMPENSADOR_EMOCIONAL:3},B:{COMPENSADOR_EMOCIONAL:1},C:{EVITADOR_FINANCIERO:2},D:{CONTROLADOR_ANSIOSO:3},E:{DESORDENADO_CRONICO:2}},
14:{A:{COMPENSADOR_EMOCIONAL:2},B:{COMPENSADOR_EMOCIONAL:3},C:{COMPENSADOR_EMOCIONAL:3},D:{DESORDENADO_CRONICO:2},E:{ORDENADO_FUNCIONAL:2}},
15:{A:{COMPENSADOR_EMOCIONAL:2},B:{AHORRADOR_SIN_PROPOSITO:2},C:{AHORRADOR_SIN_PROPOSITO:3},D:{ORDENADO_FUNCIONAL:2},E:{ASPIRACIONAL_DESALINEADO:2}},
16:{A:{ASPIRACIONAL_DESALINEADO:2},B:{CONTROLADOR_ANSIOSO:2},C:{INVERSOR_PREMATURO:2},D:{ASPIRACIONAL_DESALINEADO:3},E:{EVITADOR_FINANCIERO:2}},
17:{A:{ORDENADO_FUNCIONAL:2},B:{COMPENSADOR_EMOCIONAL:2},C:{COMPENSADOR_EMOCIONAL:2},D:{ORDENADO_FUNCIONAL:2},E:{CONTROLADOR_ANSIOSO:2}},
18:{A:{COMPENSADOR_EMOCIONAL:3},B:{COMPENSADOR_EMOCIONAL:2},C:{ASPIRACIONAL_DESALINEADO:2},D:{COMPENSADOR_EMOCIONAL:2},E:{RACIONAL_DESCONECTADO:2}},

19:{A:{COMPENSADOR_EMOCIONAL:2},B:{DESORDENADO_CRONICO:2},C:{AHORRADOR_SIN_PROPOSITO:2},D:{ORDENADO_FUNCIONAL:3},E:{EVITADOR_FINANCIERO:3}},
20:{A:{DESORDENADO_CRONICO:3},B:{DESORDENADO_CRONICO:2},C:{AHORRADOR_SIN_PROPOSITO:2},D:{ORDENADO_FUNCIONAL:3},E:{DESORDENADO_CRONICO:2}},
21:{A:{COMPENSADOR_EMOCIONAL:2},B:{ASPIRACIONAL_DESALINEADO:2},C:{DESORDENADO_CRONICO:2},D:{ORDENADO_FUNCIONAL:2},E:{RACIONAL_DESCONECTADO:2}},
22:{A:{EVITADOR_FINANCIERO:3},B:{AHORRADOR_SIN_PROPOSITO:2},C:{DESORDENADO_CRONICO:3},D:{ORDENADO_FUNCIONAL:3},E:{EVITADOR_FINANCIERO:2}},
23:{A:{DESORDENADO_CRONICO:2},B:{DESORDENADO_CRONICO:1},C:{RACIONAL_DESCONECTADO:2},D:{ORDENADO_FUNCIONAL:2},E:{ORDENADO_FUNCIONAL:3}},
24:{A:{DESORDENADO_CRONICO:3},B:{CONTROLADOR_ANSIOSO:2},C:{AHORRADOR_SIN_PROPOSITO:2},D:{ASPIRACIONAL_DESALINEADO:2},E:{DESORDENADO_CRONICO:2}},

25:{A:{EVITADOR_FINANCIERO:2},B:{ORDENADO_FUNCIONAL:2},C:{CONTROLADOR_ANSIOSO:2},D:{DESORDENADO_CRONICO:2},E:{EVITADOR_FINANCIERO:2}},
26:{A:{EVITADOR_FINANCIERO:3},B:{DESORDENADO_CRONICO:3},C:{CONTROLADOR_ANSIOSO:2},D:{ORDENADO_FUNCIONAL:2},E:{COMPENSADOR_EMOCIONAL:2}},
27:{A:{COMPENSADOR_EMOCIONAL:2},B:{AHORRADOR_SIN_PROPOSITO:2},C:{ASPIRACIONAL_DESALINEADO:2},D:{CONTROLADOR_ANSIOSO:2},E:{EVITADOR_FINANCIERO:2}},
28:{A:{ASPIRACIONAL_DESALINEADO:3},B:{CONTROLADOR_ANSIOSO:2},C:{DESORDENADO_CRONICO:2},D:{ORDENADO_FUNCIONAL:2},E:{COMPENSADOR_EMOCIONAL:2}},
29:{A:{COMPENSADOR_EMOCIONAL:2},B:{CONTROLADOR_ANSIOSO:2},C:{DESORDENADO_CRONICO:2},D:{ORDENADO_FUNCIONAL:2},E:{COMPENSADOR_EMOCIONAL:2}},
30:{A:{COMPENSADOR_EMOCIONAL:2},B:{CONTROLADOR_ANSIOSO:2},C:{COMPENSADOR_EMOCIONAL:2},D:{ORDENADO_FUNCIONAL:2},E:{ORDENADO_FUNCIONAL:3}}

};
